const DEBUG_MODE=(()=>{const value=new URLSearchParams(location.search).get('debug');if(value==='1'||value==='true')localStorage.setItem('classspace_debug','true');if(value==='0'||value==='false')localStorage.removeItem('classspace_debug');return localStorage.getItem('classspace_debug')==='true'})();
const LOCAL_MODE=DEBUG_MODE||['localhost','127.0.0.1'].includes(location.hostname)||location.protocol==='file:';
const API_BASE=LOCAL_MODE?'':'https://rinoproxs.xsrv.jp/kyoukana/api';
const demoRooms=[{id:1,name:'音楽室',building:'本館 2F',capacity:40,facilities:'ピアノ・譜面台',is_special_permission_required:false,is_closed_during_class_hours:true},{id:2,name:'理科室A',building:'本館 3F',capacity:36,facilities:'実験台・水道',is_special_permission_required:true,is_closed_during_class_hours:true},{id:3,name:'視聴覚室',building:'西館 1F',capacity:80,facilities:'プロジェクター・Wi-Fi',is_special_permission_required:false,is_closed_during_class_hours:false},{id:4,name:'多目的室',building:'体育館 1F',capacity:100,facilities:'鏡・音響設備',is_special_permission_required:false,is_closed_during_class_hours:false},{id:5,name:'美術室',building:'本館 2F',capacity:32,facilities:'作業台・流し台',is_special_permission_required:true,is_closed_during_class_hours:true}];
const initialReservations=[{id:1,room_id:1,room_name:'音楽室',group_name:'吹奏楽部',user_name:'田中先生',start_time:'2026-08-26 16:00:00',end_time:'2026-08-26 18:00:00',purpose:'夏季演奏会の練習',reservation_type:'normal',status:'active',created_at:'2026-08-20 10:00:00'},{id:2,room_id:2,room_name:'理科室A',group_name:'科学部',user_name:'佐藤 花子',start_time:'2026-08-26 17:00:00',end_time:'2026-08-26 19:00:00',purpose:'実験会',reservation_type:'normal',status:'active',created_at:'2026-08-21 10:00:00'}];
const initialGroups=[{id:1,name:'吹奏楽部',type:'club',member_role:'leader',member_count:12},{id:2,name:'フルートパート',type:'subgroup',member_role:'member',member_count:4},{id:3,name:'文化祭実行チーム',type:'temporary',member_role:'leader',member_count:8}];
const readDemoData=(key,initial)=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(value)?value:initial.map(item=>({...item}))}catch(error){console.warn(`ローカルデータを読み込めませんでした: ${key}`,error);return initial.map(item=>({...item}))}};
let demoReservations=readDemoData('classspace_demo_reservations',initialReservations),demoGroups=readDemoData('classspace_demo_groups',initialGroups),demoRequests=readDemoData('classspace_demo_requests',[]),demoNotifications=readDemoData('classspace_demo_notifications',[]);
const saveDemoData=()=>{localStorage.setItem('classspace_demo_reservations',JSON.stringify(demoReservations));localStorage.setItem('classspace_demo_groups',JSON.stringify(demoGroups));localStorage.setItem('classspace_demo_requests',JSON.stringify(demoRequests));localStorage.setItem('classspace_demo_notifications',JSON.stringify(demoNotifications))};
const currentDebugUser=()=>JSON.parse(localStorage.getItem('classspace_user')||'null')||{id:0,name:'デバッグ開発者',role:'developer',email:'debug@example.test'};
const parseBody=options=>{try{return JSON.parse(options.body||'{}')}catch{return{}}};
const minutes=value=>{const match=String(value).match(/(\d{1,2}):(\d{2})/);return match?Number(match[1])*60+Number(match[2]):0};
const overlaps=(aStart,aEnd,bStart,bEnd)=>new Date(aStart.replace(' ','T'))<new Date(bEnd.replace(' ','T'))&&new Date(aEnd.replace(' ','T'))>new Date(bStart.replace(' ','T'));
function validateDemoReservation(item,ignoreId){const room=demoRooms.find(r=>Number(r.id)===Number(item.room_id));if(!room)throw new Error('教室が見つかりません');const start=new Date(String(item.start_time).replace(' ','T')),end=new Date(String(item.end_time).replace(' ','T'));if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)throw new Error('終了時刻は開始時刻より後にしてください');if(end-start>4*60*60*1000)throw new Error('予約は4時間以内にしてください');const day=start.getDay();if(room.is_closed_during_class_hours&&day>=1&&day<=5&&minutes(item.start_time)<930&&minutes(item.end_time)>510)throw new Error('平日の授業時間帯は予約できません');if(demoReservations.some(r=>r.status==='active'&&Number(r.room_id)===room.id&&r.id!==ignoreId&&overlaps(item.start_time,item.end_time,r.start_time,r.end_time)))throw new Error('その時間帯はすでに予約されています');return room}
async function demoApi(path,options={}){const method=(options.method||'GET').toUpperCase(),body=parseBody(options);if(path==='/rooms')return{rooms:demoRooms};if(path.startsWith('/reservations?')){const date=new URLSearchParams(path.split('?')[1]).get('date');return{reservations:demoReservations.filter(r=>r.status==='active'&&(!date||r.start_time.slice(0,10)===date))}}if(path==='/reservations'&&method==='POST'){const room=validateDemoReservation(body);const id=Date.now();const user=currentDebugUser();demoReservations.push({id,...body,room_id:Number(body.room_id),room_name:room.name,user_name:user.name,group_name:demoGroups.find(g=>Number(g.id)===Number(body.group_id))?.name||'マイグループ',reservation_type:body.reservation_type||'normal',status:'active',created_at:new Date().toISOString()});saveDemoData();return{reservation_id:id}}if(/^\/reservations\/\d+$/.test(path)){const id=Number(path.split('/')[2]),item=demoReservations.find(r=>r.id===id);if(!item)throw new Error('予約が見つかりません');if(method==='GET')return{reservation:item};if(method==='PUT'){validateDemoReservation({...item,...body},id);Object.assign(item,body);saveDemoData();return{ok:true}}if(method==='DELETE'){item.status='cancelled';saveDemoData();return{ok:true}}}if(path==='/groups'&&method==='GET')return{groups:demoGroups};if(path==='/groups'&&method==='POST'){const id=Date.now();demoGroups.push({id,name:String(body.name||'').trim(),type:body.type||'temporary',member_role:'leader',member_count:1});saveDemoData();return{group_id:id}}if(/^\/groups\/\d+$/.test(path)&&method==='DELETE'){const id=Number(path.split('/')[2]);demoGroups=demoGroups.filter(g=>g.id!==id);saveDemoData();return{ok:true}}if(path==='/requests'&&method==='GET')return{requests:demoRequests};if(path==='/requests'&&method==='POST'){const id=Date.now(),user=currentDebugUser(),request={id,...body,status:'pending',applicant_name:user.name,room_name:demoRooms.find(r=>Number(r.id)===Number(body.room_id))?.name||'教室',created_at:new Date().toISOString()};demoRequests.unshift(request);demoNotifications.unshift({id:Date.now()+1,title:'新しい申請があります',content:`${user.name}さんから申請が届きました`,is_read:false,created_at:new Date().toISOString()});saveDemoData();return{request_id:id}}if(/^\/requests\/\d+\/(approve|reject)$/.test(path)&&method==='PUT'){const id=Number(path.split('/')[2]),request=demoRequests.find(r=>r.id===id);if(!request)throw new Error('申請が見つかりません');request.status=path.endsWith('approve')?'approved':'rejected';request.rejection_reason=body.reason||null;demoNotifications.unshift({id:Date.now(),title:`申請を${request.status==='approved'?'承認':'却下'}しました`,content:request.message||'',is_read:false,created_at:new Date().toISOString()});saveDemoData();return{ok:true}}if(path==='/notifications')return{notifications:demoNotifications};if(path==='/notifications/read'&&method==='PUT'){demoNotifications.forEach(n=>n.is_read=true);saveDemoData();return{ok:true}}if(path==='/admin/settings')return{settings:[]};return{ok:true}}
async function api(path,options={}){if(LOCAL_MODE)return demoApi(path,options);const token=localStorage.getItem('classspace_token');if(!token&&path.startsWith('/reservations?'))return{reservations:[]};const headers={...(options.headers||{}),'Content-Type':'application/json'};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API_BASE}${path}`,{...options,headers});const text=await response.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={error:text}}}if(!response.ok)throw new Error(typeof data.error==='string'?data.error:'通信に失敗しました');return data}
