const DEBUG_MODE=(()=>{const query=new URLSearchParams(location.search).get('debug');if(query==='1'||query==='true')localStorage.setItem('classspace_debug','true');if(query==='0'||query==='false')localStorage.removeItem('classspace_debug');return localStorage.getItem('classspace_debug')==='true'})();
const LOCAL_MODE=DEBUG_MODE||['localhost','127.0.0.1'].includes(location.hostname)||location.protocol==='file:';
const API_BASE=LOCAL_MODE?'':'https://rinoproxs.xsrv.jp/kyoukana/api';
const demoRooms=[{id:1,name:'音楽室',building:'本館 2F',capacity:40,is_closed_during_class_hours:true},{id:2,name:'理科室A',building:'本館 3F',capacity:36,is_closed_during_class_hours:true},{id:3,name:'視聴覚室',building:'西館 1F',capacity:80,is_closed_during_class_hours:false},{id:4,name:'多目的室',building:'体育館 1F',capacity:100,is_closed_during_class_hours:false},{id:5,name:'美術室',building:'本館 2F',capacity:32,is_closed_during_class_hours:true}];
const initialReservations=[{id:1,room_id:1,room_name:'音楽室',group_name:'吹奏楽部',user_name:'田中先生',start_time:'2026-08-26 16:00:00',end_time:'2026-08-26 18:00:00',purpose:'夏季演奏会の練習'},{id:2,room_id:2,room_name:'理科室A',group_name:'科学部',user_name:'佐藤 花子',start_time:'2026-08-26 17:00:00',end_time:'2026-08-26 19:00:00',purpose:'実験会'}];
const initialGroups=[{id:1,name:'吹奏楽部',type:'club',member_role:'leader'},{id:2,name:'フルートパート',type:'subgroup',member_role:'member'},{id:3,name:'文化祭実行チーム',type:'temporary',member_role:'leader'}];
const readDemoData=(key,initial)=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(value)?value:initial}catch(error){console.warn(`ローカルデータを読み込めませんでした: ${key}`,error);return initial}};
let demoReservations=readDemoData('classspace_demo_reservations',initialReservations);
let demoGroups=readDemoData('classspace_demo_groups',initialGroups);
const saveDemoData=()=>{localStorage.setItem('classspace_demo_reservations',JSON.stringify(demoReservations));localStorage.setItem('classspace_demo_groups',JSON.stringify(demoGroups))};
async function api(path,options={}){const token=localStorage.getItem('classspace_token');if(LOCAL_MODE)return demoApi(path,options);if(!token&&path.startsWith('/reservations?'))return{reservations:[]};const headers={...(options.headers||{})};if(!('Content-Type' in headers)&&!('content-type' in headers))headers['Content-Type']='application/json';if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API_BASE}${path}`,{...options,headers});const text=await response.text();let data={};if(text){try{data=JSON.parse(text)}catch{return text}}if(!response.ok)throw new Error(data.error||'通信に失敗しました');return data}
async function demoApi(path,options={}){if(path.startsWith('/reservations/')&&options.method==='DELETE'){const id=Number(path.split('/')[2]),item=demoReservations.find(reservation=>reservation.id===id);if(item)item.status='cancelled';saveDemoData();return{ok:true}}if(path.startsWith('/groups/')&&options.method==='DELETE'){const id=Number(path.split('/')[2]),index=demoGroups.findIndex(group=>group.id===id);if(index>=0)demoGroups.splice(index,1);saveDemoData();return{ok:true}}if(path==='/reservations'&&options.method==='POST'){const item=JSON.parse(options.body),room=demoRooms.find(r=>r.id==item.room_id);if(!room)throw new Error('教室が見つかりません');const id=Date.now();demoReservations.push({id,...item,room_name:room.name,group_name:'マイグループ',user_name:'デバッグユーザー'});saveDemoData();return{reservation_id:id}}if(path==='/groups'&&options.method==='POST'){const item=JSON.parse(options.body),id=Date.now();demoGroups.push({id,...item,member_role:'leader'});saveDemoData();return{group_id:id}}if(path.startsWith('/rooms'))return{rooms:demoRooms};if(path.startsWith('/reservations?')){const date=new URLSearchParams(path.split('?')[1]).get('date');return{reservations:demoReservations.filter(reservation=>reservation.status!=='cancelled'&&(!date||reservation.start_time.slice(0,10)===date))}}if(path==='/groups')return{groups:demoGroups};if(path==='/notifications')return{notifications:[]};return{ok:true}}
