document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#notification-button').onclick=async()=>{try{const data=await api('/notifications');const items=data.notifications||[];modal('通知',items.length?items.map(item=>`<article class="request-card"><h3>${item.title}</h3><p>${item.content}</p></article>`).join(''):'<p>通知はありません。</p>')}catch(error){showToast(error.message)}}});
const mobileLayoutStyle=document.createElement('style');mobileLayoutStyle.textContent='@media (max-width:767px){.app-shell{display:block}.sidebar{width:100%;height:auto;min-height:0;padding:10px 12px;display:block}.brand{padding:0 0 10px}.brand small{display:none}#main-nav{display:flex;gap:4px}.nav-item{width:auto;flex:1;justify-content:center;gap:4px;padding:10px 4px;margin:0;font-size:11px}.nav-item span{width:auto;font-size:16px}.sidebar-footer{display:none}.main{width:100%}}';document.head.appendChild(mobileLayoutStyle);
const ROLE_LABEL={student:'生徒',leader:'部長',teacher:'先生',admin:'管理者',developer:'開発者'};let sessionUser=DEBUG_MODE?{id:0,name:'デバッグユーザー',role:'developer'}:JSON.parse(localStorage.getItem('classspace_user')||'null');
if(DEBUG_MODE)localStorage.setItem('classspace_user',JSON.stringify(sessionUser));
function initAuth(){const user=sessionUser||{name:'未ログイン',role:'student'};document.querySelector('#user-name').textContent=user.name;document.querySelector('#user-role').textContent=sessionUser?ROLE_LABEL[user.role]||'生徒':'ログインしてください';document.querySelector('#user-avatar').textContent=user.name.slice(0,1);const loginButton=document.querySelector('#google-login');if(loginButton)loginButton.classList.toggle('hidden',Boolean(sessionUser));if(sessionUser&&['admin','developer'].includes(sessionUser.role))document.querySelectorAll('.admin-only').forEach(el=>el.classList.remove('hidden'))}
async function signInWithGoogle(credential){try{const result=await api('/auth/google',{method:'POST',body:JSON.stringify({credential})});sessionUser=result.user;localStorage.setItem('classspace_user',JSON.stringify(sessionUser));localStorage.setItem('classspace_token',result.token);initAuth();await loadTimeline();showToast('ログインしました')}catch(error){showToast(error.message)}}
function setupGoogleSignIn(){const topActions=document.querySelector('.top-actions');if(DEBUG_MODE||!topActions||sessionUser)return;const button=document.createElement('div');button.id='google-login';button.className='primary-button';topActions.prepend(button);const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.defer=true;script.onload=()=>{window.google.accounts.id.initialize({client_id:'312123690769-0gsq6inm3hoer3ivk9gf3fkrqhgo998t.apps.googleusercontent.com',callback:response=>signInWithGoogle(response.credential)});window.google.accounts.id.renderButton(button,{theme:'outline',size:'large',text:'signin_with',shape:'rectangular'})};document.head.appendChild(script)}
document.addEventListener('DOMContentLoaded',setupGoogleSignIn);
const responsiveStyle=document.createElement('style');responsiveStyle.textContent='html{overflow-x:hidden!important}body{overflow-x:hidden!important}@media (max-width:767px){.topbar .top-actions{width:100%!important;min-width:0!important;max-width:100%!important;overflow:hidden}.topbar{padding:18px 16px;align-items:flex-start;flex-direction:column;gap:14px}.topbar h1{font-size:20px;line-height:1.35}.modal{width:calc(100vw - 28px);max-width:520px;max-height:calc(100vh - 28px);overflow-y:auto}.modal-footer{flex-wrap:wrap}.modal-footer button{flex:1 1 140px}}';document.head.appendChild(responsiveStyle);
