<?php
declare(strict_types=1);
require_once __DIR__ . '/lib/auth.php';
require_once __DIR__ . '/lib/mailer.php';

$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if (in_array($origin, (array) config('allowed_origins', []), true)) { header("Access-Control-Allow-Origin: $origin"); header('Access-Control-Allow-Credentials: true'); }
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Authorization'); header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') exit;

$method = $_SERVER['REQUEST_METHOD']; $path = trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');
$path = preg_replace('#^.*?/api/?#', '', $path); $parts = $path === '' ? [] : explode('/', $path); $body = requestBody(); $pdo = Database::connection();
try {
	if ($parts === ['auth','google'] && $method === 'POST') jsonResponse(googleLogin((string) ($body['credential'] ?? $body['id_token'] ?? '')));
	if ($parts === ['rooms'] && $method === 'GET') {
		$rows = $pdo->query('SELECT r.*, u.name responsible_name FROM rooms r LEFT JOIN users u ON u.id=r.responsible_user_id ORDER BY r.building,r.name')->fetchAll(); jsonResponse(['rooms'=>$rows]);
	}
	if ($parts === ['reservations'] && $method === 'GET') {
		currentUser(); $date = $_GET['date'] ?? date('Y-m-d'); $stmt=$pdo->prepare("SELECT r.*, rm.name room_name, rm.building, g.name group_name, u.name user_name FROM reservations r JOIN rooms rm ON rm.id=r.room_id LEFT JOIN `groups` g ON g.id=r.group_id JOIN users u ON u.id=r.user_id WHERE r.status='active' AND r.start_time < ? AND r.end_time > ? ORDER BY r.start_time"); $stmt->execute(["$date 23:59:59", "$date 00:00:00"]); jsonResponse(['reservations'=>$stmt->fetchAll(),'date'=>$date]);
	}
	if ($parts === ['reservations'] && $method === 'POST') {
		$user=currentUser(); $roomId=(int)($body['room_id']??0); $start=new DateTime((string)($body['start_time']??'')); $end=new DateTime((string)($body['end_time']??'')); if($end <= $start) fail('終了時刻は開始時刻より後にしてください');
		$maxDays=in_array($user['role'],['admin','developer'],true)?365:7; if($start > new DateTime("+$maxDays days")) fail("予約は{$maxDays}日先までです");
		$roomStmt=$pdo->prepare('SELECT * FROM rooms WHERE id=? FOR UPDATE'); $pdo->beginTransaction(); $roomStmt->execute([$roomId]); $room=$roomStmt->fetch(); if(!$room){$pdo->rollBack();fail('教室が見つかりません',404);} if((int)($room['is_disabled']??0)===1){$pdo->rollBack();fail('この教室は現在利用停止中です',409);}
		$weekday=(int)$start->format('N'); $date=$start->format('Y-m-d'); if($end->getTimestamp()-$start->getTimestamp()>14400){$pdo->rollBack();fail('予約は4時間以内にしてください');} if($room['is_closed_during_class_hours'] && $weekday<=5 && $start < new DateTime("$date 15:30:00") && $end > new DateTime("$date 08:30:00")){ $pdo->rollBack(); fail('平日の授業時間帯は予約できません'); }
		$stmt=$pdo->prepare("SELECT COUNT(*) FROM reservations WHERE room_id=? AND status='active' AND start_time<? AND end_time>? FOR UPDATE"); $stmt->execute([$roomId,$end->format('Y-m-d H:i:s'),$start->format('Y-m-d H:i:s')]); if((int)$stmt->fetchColumn()>0){$pdo->rollBack();fail('その時間帯はすでに予約されています',409);}
		$stmt=$pdo->prepare('INSERT INTO reservations(room_id,group_id,user_id,start_time,end_time,reservation_type,purpose) VALUES(?,?,?,?,?,?,?)'); $stmt->execute([$roomId,$body['group_id']??null,$user['id'],$start->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$body['reservation_type']??'normal',$body['purpose']??null]); $id=$pdo->lastInsertId(); $pdo->commit(); jsonResponse(['reservation_id'=>(int)$id],201);
	}
	if (($parts[0] ?? '') === 'reservations' && isset($parts[1]) && $method === 'PUT') { $user=currentUser(); $id=(int)$parts[1]; $existing=$pdo->prepare('SELECT * FROM reservations WHERE id=?');$existing->execute([$id]);$reservation=$existing->fetch();if(!$reservation)fail('予約が見つかりません',404);if($reservation['user_id']!=$user['id']&&!in_array($user['role'],['teacher','admin','developer'],true))fail('予約を変更できません',403);if(isset($body['status'])){if(!in_array($body['status'],['active','cancelled','overridden'],true))fail('不正な予約状態です');$stmt=$pdo->prepare('UPDATE reservations SET status=? WHERE id=? AND status="active"');$stmt->execute([$body['status'],$id]);}else{$start=new DateTime((string)($body['start_time']??$reservation['start_time']));$end=new DateTime((string)($body['end_time']??$reservation['end_time']));if($end<=$start)fail('終了時刻は開始時刻より後にしてください');$stmt=$pdo->prepare("SELECT COUNT(*) FROM reservations WHERE room_id=? AND status='active' AND id<>? AND start_time<? AND end_time>?");$stmt->execute([(int)($body['room_id']??$reservation['room_id']),$id,$end->format('Y-m-d H:i:s'),$start->format('Y-m-d H:i:s')]);if((int)$stmt->fetchColumn()>0)fail('その時間帯はすでに予約されています',409);$stmt=$pdo->prepare('UPDATE reservations SET room_id=?,group_id=?,start_time=?,end_time=?,purpose=? WHERE id=?');$stmt->execute([(int)($body['room_id']??$reservation['room_id']),$body['group_id']??$reservation['group_id'],$start->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$body['purpose']??$reservation['purpose'],$id]);}if(!$stmt->rowCount())fail('予約を変更できません',403);jsonResponse(['ok'=>true]); }
	if (($parts[0] ?? '') === 'reservations' && isset($parts[1]) && $method === 'DELETE') { $user=currentUser(); $id=(int)$parts[1]; $stmt=$pdo->prepare("UPDATE reservations SET status='cancelled' WHERE id=? AND status='active' AND (user_id=? OR ? IN ('teacher','admin','developer'))"); $stmt->execute([$id,$user['id'],$user['role']]); if(!$stmt->rowCount()) fail('予約を取り消せません',403); jsonResponse(['ok'=>true]); }
	if ($parts === ['reservations','auto-allocate'] && $method === 'POST') {
		$user=requireRole('leader'); $items=$body['items']??[]; $rooms=$pdo->query('SELECT * FROM rooms ORDER BY capacity DESC,name')->fetchAll(); $allocated=[]; $unallocated=[];
		usort($items, static fn(array $a,array $b): int => (($a['reservation_type']??'normal')==='recurring'?0:1) <=> (($b['reservation_type']??'normal')==='recurring'?0:1));
		foreach($items as $item){$placed=false;$start=new DateTime($item['start_time']);$end=new DateTime($item['end_time']);foreach($rooms as $room){$s=$pdo->prepare("SELECT COUNT(*) FROM reservations WHERE room_id=? AND status='active' AND start_time<? AND end_time>?");$s->execute([$room['id'],$end->format('Y-m-d H:i:s'),$start->format('Y-m-d H:i:s')]);$weekday=(int)$start->format('N');$locked=$room['is_closed_during_class_hours']&&$weekday<=5&&$start<new DateTime($start->format('Y-m-d').' 15:30:00')&&$end>new DateTime($start->format('Y-m-d').' 08:30:00');if((int)$s->fetchColumn()===0&&!$locked){$ins=$pdo->prepare('INSERT INTO reservations(room_id,group_id,user_id,start_time,end_time,reservation_type,purpose) VALUES(?,?,?,?,?,?,?)');$ins->execute([$room['id'],$item['group_id']??null,$user['id'],$start->format('Y-m-d H:i:s'),$end->format('Y-m-d H:i:s'),$item['reservation_type']??'normal',$item['purpose']??null]);$allocated[]=['request'=>$item,'room_id'=>(int)$room['id'],'reservation_id'=>(int)$pdo->lastInsertId()];$placed=true;break;}}if(!$placed)$unallocated[]=$item;}
		jsonResponse(['allocated'=>$allocated,'unallocated'=>$unallocated]);
	}
	if ($parts === ['groups'] && $method === 'GET') { $user=currentUser(); $stmt=$pdo->prepare('SELECT g.*, gm.role member_role FROM `groups` g JOIN group_members gm ON gm.group_id=g.id WHERE gm.user_id=? ORDER BY g.name'); $stmt->execute([$user['id']]); jsonResponse(['groups'=>$stmt->fetchAll()]); }
	if ($parts === ['groups'] && $method === 'POST') { $user=currentUser(); $pdo->beginTransaction(); $stmt=$pdo->prepare('INSERT INTO `groups`(name,type,parent_id,leader_user_id) VALUES(?,?,?,?)'); $stmt->execute([$body['name'],$body['type']??'temporary',$body['parent_id']??null,$user['id']]); $id=$pdo->lastInsertId(); $pdo->prepare('INSERT INTO group_members(group_id,user_id,role) VALUES(?,?,?)')->execute([$id,$user['id'],'leader']); $pdo->commit(); jsonResponse(['group_id'=>(int)$id],201); }
	if (($parts[0] ?? '') === 'groups' && isset($parts[1]) && $method === 'DELETE') { $user=currentUser(); $id=(int)$parts[1]; $stmt=$pdo->prepare('DELETE FROM `groups` WHERE id=? AND (leader_user_id=? OR ? IN ("admin","developer"))'); $stmt->execute([$id,$user['id'],$user['role']]); if(!$stmt->rowCount()) fail('グループを削除できません',403); jsonResponse(['ok'=>true]); }
	if ($parts === ['requests'] && $method === 'POST') { $user=currentUser(); $room=(int)$body['room_id']; $target=$body['target_reservation_id']??null; $approver=null; if($target){$s=$pdo->prepare('SELECT user_id FROM reservations WHERE id=?');$s->execute([$target]);$approver=$s->fetchColumn()?:null;} if(!$approver){$s=$pdo->prepare('SELECT responsible_user_id FROM rooms WHERE id=?');$s->execute([$room]);$approver=$s->fetchColumn()?:null;} if(!$approver) fail('承認者が設定されていません'); $s=$pdo->prepare('INSERT INTO requests(request_type,target_reservation_id,room_id,applicant_user_id,approver_user_id,requested_start_time,requested_end_time,message) VALUES(?,?,?,?,?,?,?,?)'); $s->execute([$body['request_type'],$target,$room,$user['id'],$approver,$body['requested_start_time'],$body['requested_end_time'],$body['message']??null]); notifyUser($pdo,(int)$approver,'新しい申請があります',"{$user['name']}さんから申請が届きました"); jsonResponse(['request_id'=>(int)$pdo->lastInsertId()],201); }
	if ($parts === ['requests'] && $method === 'GET') { $user=currentUser(); $s=$pdo->prepare('SELECT q.*, r.name room_name, u.name applicant_name FROM requests q JOIN rooms r ON r.id=q.room_id JOIN users u ON u.id=q.applicant_user_id WHERE q.approver_user_id=? OR q.applicant_user_id=? ORDER BY q.created_at DESC'); $s->execute([$user['id'],$user['id']]); jsonResponse(['requests'=>$s->fetchAll()]); }
	if ($parts === ['notifications'] && $method === 'GET') { $user=currentUser(); $s=$pdo->prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50');$s->execute([$user['id']]);jsonResponse(['notifications'=>$s->fetchAll()]); }
	if (count($parts)===3 && $parts[0]==='requests' && in_array($parts[2],['approve','reject'],true) && $method==='PUT') { $user=currentUser(); $id=(int)$parts[1]; $s=$pdo->prepare('SELECT * FROM requests WHERE id=? AND status="pending"');$s->execute([$id]);$req=$s->fetch();if(!$req||($req['approver_user_id']!=$user['id']&&!in_array($user['role'],['admin','developer'],true)))fail('申請を処理できません',403);if($parts[2]==='reject'&&trim((string)($body['reason']??''))==='')fail('却下理由を入力してください');$status=$parts[2]==='approve'?'approved':'rejected';$pdo->beginTransaction();$pdo->prepare('UPDATE requests SET status=?,rejection_reason=? WHERE id=?')->execute([$status,$body['reason']??null,$id]);if($status==='approved'&&$req['request_type']==='transfer'&&$req['target_reservation_id']){$old=$pdo->prepare('SELECT * FROM reservations WHERE id=? AND status="active" FOR UPDATE');$old->execute([$req['target_reservation_id']]);$reservation=$old->fetch();if(!$reservation){$pdo->rollBack();fail('対象の予約はすでに変更されています',409);}$pdo->prepare('UPDATE reservations SET status="overridden" WHERE id=?')->execute([$reservation['id']]);$pdo->prepare('INSERT INTO reservations(room_id,group_id,user_id,start_time,end_time,purpose) VALUES(?,?,?,?,?,?)')->execute([$reservation['room_id'],null,$req['applicant_user_id'],$reservation['start_time'],$reservation['end_time'],$reservation['purpose']]);}elseif($status==='approved'&&$req['request_type']==='share'&&$req['target_reservation_id']){$pdo->prepare('UPDATE reservations SET shared_user_id=? WHERE id=?')->execute([$req['applicant_user_id'],$req['target_reservation_id']]);}$pdo->commit();notifyUser($pdo,(int)$req['applicant_user_id'],'申請が'.($status==='approved'?'承認':'却下').'されました',$body['reason']??'申請の処理結果を確認してください');jsonResponse(['ok'=>true]); }
	if ($parts === ['admin','settings'] && $method === 'GET') { requireRole('admin'); jsonResponse(['settings'=>$pdo->query('SELECT * FROM system_settings')->fetchAll()]); }
	fail('エンドポイントが見つかりません',404);
} catch (Throwable $e) { if($pdo->inTransaction())$pdo->rollBack(); error_log($e->getMessage()); fail('サーバーエラーが発生しました',500); }
