-- XServerのphpMyAdminで対象データベースを選択してから実行してください。
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, google_id VARCHAR(255) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, role ENUM('developer','admin','teacher','leader','student') NOT NULL DEFAULT 'student', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE `groups` (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, type ENUM('club','subgroup','temporary') NOT NULL DEFAULT 'temporary', parent_id INT NULL, leader_user_id INT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (parent_id) REFERENCES `groups`(id) ON DELETE SET NULL, FOREIGN KEY (leader_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE group_members (id INT AUTO_INCREMENT PRIMARY KEY, group_id INT NOT NULL, user_id INT NOT NULL, role ENUM('leader','member') NOT NULL DEFAULT 'member', UNIQUE KEY group_user (group_id,user_id), FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE rooms (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, building VARCHAR(50), capacity INT DEFAULT 40, facilities TEXT NULL, is_special_permission_required BOOLEAN DEFAULT FALSE, responsible_user_id INT NULL, is_closed_during_class_hours BOOLEAN DEFAULT TRUE, is_disabled BOOLEAN DEFAULT FALSE, disabled_reason VARCHAR(255) NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (responsible_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE reservations (id INT AUTO_INCREMENT PRIMARY KEY, room_id INT NOT NULL, group_id INT NULL, user_id INT NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, reservation_type ENUM('recurring','normal','event_priority') NOT NULL DEFAULT 'normal', status ENUM('active','cancelled','overridden') NOT NULL DEFAULT 'active', purpose VARCHAR(255), cancel_reason VARCHAR(255) NULL, shared_user_id INT NULL, shared_group_id INT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX room_time (room_id,status,start_time,end_time), INDEX user_created (user_id,created_at), FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE, FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE SET NULL, FOREIGN KEY (shared_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE requests (id INT AUTO_INCREMENT PRIMARY KEY, request_type ENUM('permission','share','transfer') NOT NULL, target_reservation_id INT NULL, room_id INT NOT NULL, applicant_user_id INT NOT NULL, approver_user_id INT NULL, requested_start_time DATETIME NOT NULL, requested_end_time DATETIME NOT NULL, message TEXT, status ENUM('pending','approved','rejected','cancelled') DEFAULT 'pending', rejection_reason TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (target_reservation_id) REFERENCES reservations(id) ON DELETE SET NULL, FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE, FOREIGN KEY (applicant_user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (approver_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE notifications (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, is_read BOOLEAN DEFAULT FALSE, link_url VARCHAR(255), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX user_read (user_id,is_read), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE system_settings (setting_key VARCHAR(50) PRIMARY KEY, setting_value TEXT NOT NULL, description VARCHAR(255));
INSERT INTO system_settings VALUES ('class_hour_start','08:30','授業開始'),('class_hour_end','15:30','授業終了'),('general_booking_lead_days','7','一般予約可能日数'),('admin_booking_lead_days','365','管理者予約可能日数');
